[package]
name = "neron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
num-traits = "0.2.16"
ndarray = "0.15.3"
# egui = "0.22"
# eframe = "0.22"
# egui_plot = "0.29.0"
